# Generated by Django 3.2.18 on 2023-08-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quote_jokes_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='jokes',
            name='joke',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(max_length=2000),
        ),
    ]
